# Site settings
title: João França
description: João França's little corner
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: João França
user_description: Hello there!
user_title: Data Scientist / Engineer


# Google-analytics
google-analytics:
  id: "UA-165979555-1"

exclude: ['package.json', 'src' , 'node_modules']
